create table friendships (
    id           bigint      generated by default as identity primary key,
    user_low_id  bigint      not null references users (id) on delete cascade,
    user_high_id bigint      not null references users (id) on delete cascade,
    created_by   bigint      references users (id) on delete set null,
    created_at   timestamptz not null default now(),
    constraint uq_friendships unique (user_low_id, user_high_id),
    constraint ck_friendships_order check (user_low_id < user_high_id)
);
create index idx_friendships_user_low  on friendships (user_low_id);
create index idx_friendships_user_high on friendships (user_high_id);

create table deck_suggestions (
    id             bigint       generated by default as identity primary key,
    from_user_id   bigint       not null references users (id) on delete cascade,
    to_user_id     bigint       not null references users (id) on delete cascade,
    source_deck_id bigint       references decks (id) on delete set null,
    deck_name      varchar(160) not null,
    format         varchar(32)  not null,
    message        varchar(500),
    cards          jsonb        not null default '[]'::jsonb,
    status           varchar(16)  not null default 'NEW',
    imported_deck_id bigint       references decks (id) on delete set null,
    created_at       timestamptz  not null default now(),
    resolved_at      timestamptz
);
create index idx_deck_suggestions_to_user   on deck_suggestions (to_user_id, status);
create index idx_deck_suggestions_from_user on deck_suggestions (from_user_id);

alter table decks add column suggested_by_user_id bigint references users (id) on delete set null;
create index idx_decks_suggested_by on decks (suggested_by_user_id);
