create extension if not exists pg_trgm;

create table sets (
    id           bigint generated by default as identity primary key,
    code         varchar(16)  not null unique,
    name         varchar(255) not null,
    set_type     varchar(64),
    released_at  date,
    card_count   integer,
    scryfall_id  uuid,
    icon_svg_uri varchar(512),
    created_at   timestamptz  not null default now(),
    updated_at   timestamptz  not null default now()
);
create index idx_sets_name         on sets (name);
create index idx_sets_set_type     on sets (set_type);
create index idx_sets_released_at  on sets (released_at);
create index idx_sets_card_count   on sets (card_count);
create index idx_sets_scryfall_id  on sets (scryfall_id);
create index idx_sets_icon_svg_uri on sets (icon_svg_uri);
create index idx_sets_created_at   on sets (created_at);
create index idx_sets_updated_at   on sets (updated_at);

create table card_oracles (
    id             bigint generated by default as identity primary key,
    oracle_id      uuid         not null unique,
    name           varchar(512) not null,
    mana_cost      varchar(256),
    mana_value     numeric,
    type_line      varchar(512),
    oracle_text    text,
    colors         varchar(16),
    color_identity varchar(16),
    power          varchar(16),
    toughness      varchar(16),
    loyalty        varchar(16),
    keywords       text,
    layout         varchar(64),
    reserved       boolean      not null default false,
    edhrec_rank    integer,
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now()
);
create index idx_card_oracles_name           on card_oracles (name);
create index idx_card_oracles_name_lower     on card_oracles (lower(name));
create index idx_card_oracles_name_trgm      on card_oracles using gin (name gin_trgm_ops);
create index idx_card_oracles_mana_cost      on card_oracles (mana_cost);
create index idx_card_oracles_mana_value     on card_oracles (mana_value);
create index idx_card_oracles_type_line      on card_oracles (type_line);
create index idx_card_oracles_type_line_trgm on card_oracles using gin (type_line gin_trgm_ops);
create index idx_card_oracles_oracle_text    on card_oracles using gin (oracle_text gin_trgm_ops);
create index idx_card_oracles_colors         on card_oracles (colors);
create index idx_card_oracles_color_identity on card_oracles (color_identity);
create index idx_card_oracles_power          on card_oracles (power);
create index idx_card_oracles_toughness      on card_oracles (toughness);
create index idx_card_oracles_loyalty        on card_oracles (loyalty);
create index idx_card_oracles_keywords       on card_oracles using gin (keywords gin_trgm_ops);
create index idx_card_oracles_layout         on card_oracles (layout);
create index idx_card_oracles_reserved       on card_oracles (reserved);
create index idx_card_oracles_edhrec_rank    on card_oracles (edhrec_rank);
create index idx_card_oracles_created_at     on card_oracles (created_at);
create index idx_card_oracles_updated_at     on card_oracles (updated_at);

create table card_printings (
    id                bigint generated by default as identity primary key,
    scryfall_id       uuid         not null unique,
    oracle_card_id    bigint       not null references card_oracles (id) on delete cascade,
    set_id            bigint       references sets (id) on delete set null,
    set_code          varchar(16),
    collector_number  varchar(32),
    rarity            varchar(32),
    artist            varchar(255),
    flavor_text       text,
    lang              varchar(8)   not null default 'en',
    layout            varchar(64),
    border_color      varchar(32),
    frame             varchar(32),
    promo             boolean      not null default false,
    variation         boolean      not null default false,
    full_art          boolean      not null default false,
    image_small       varchar(512),
    image_normal      varchar(512),
    image_large       varchar(512),
    image_png         varchar(512),
    image_art_crop    varchar(512),
    image_border_crop varchar(512),
    released_at       date,
    scryfall_uri      varchar(512),
    created_at        timestamptz  not null default now(),
    updated_at        timestamptz  not null default now()
);
create index idx_card_printings_oracle_card_id    on card_printings (oracle_card_id);
create index idx_card_printings_set_id            on card_printings (set_id);
create index idx_card_printings_set_code          on card_printings (set_code);
create index idx_card_printings_collector_number  on card_printings (collector_number);
create index idx_card_printings_set_code_number   on card_printings (set_code, collector_number);
create index idx_card_printings_rarity            on card_printings (rarity);
create index idx_card_printings_artist            on card_printings (artist);
create index idx_card_printings_flavor_text       on card_printings using gin (flavor_text gin_trgm_ops);
create index idx_card_printings_lang              on card_printings (lang);
create index idx_card_printings_layout            on card_printings (layout);
create index idx_card_printings_border_color      on card_printings (border_color);
create index idx_card_printings_frame             on card_printings (frame);
create index idx_card_printings_promo             on card_printings (promo);
create index idx_card_printings_variation         on card_printings (variation);
create index idx_card_printings_full_art          on card_printings (full_art);
create index idx_card_printings_image_small       on card_printings (image_small);
create index idx_card_printings_image_normal      on card_printings (image_normal);
create index idx_card_printings_image_large       on card_printings (image_large);
create index idx_card_printings_image_png         on card_printings (image_png);
create index idx_card_printings_image_art_crop    on card_printings (image_art_crop);
create index idx_card_printings_image_border_crop on card_printings (image_border_crop);
create index idx_card_printings_released_at       on card_printings (released_at);
create index idx_card_printings_scryfall_uri      on card_printings (scryfall_uri);
create index idx_card_printings_created_at        on card_printings (created_at);
create index idx_card_printings_updated_at        on card_printings (updated_at);

create table card_faces (
    id           bigint generated by default as identity primary key,
    printing_id  bigint       not null references card_printings (id) on delete cascade,
    face_index   integer      not null,
    name         varchar(512) not null,
    mana_cost    varchar(256),
    type_line    varchar(512),
    oracle_text  text,
    colors       varchar(16),
    power        varchar(16),
    toughness    varchar(16),
    loyalty      varchar(16),
    image_small  varchar(512),
    image_normal varchar(512),
    image_large  varchar(512),
    image_png    varchar(512),
    unique (printing_id, face_index)
);
create index idx_card_faces_printing_id  on card_faces (printing_id);
create index idx_card_faces_face_index   on card_faces (face_index);
create index idx_card_faces_name         on card_faces (name);
create index idx_card_faces_name_trgm    on card_faces using gin (name gin_trgm_ops);
create index idx_card_faces_mana_cost    on card_faces (mana_cost);
create index idx_card_faces_type_line    on card_faces (type_line);
create index idx_card_faces_oracle_text  on card_faces using gin (oracle_text gin_trgm_ops);
create index idx_card_faces_colors       on card_faces (colors);
create index idx_card_faces_power        on card_faces (power);
create index idx_card_faces_toughness    on card_faces (toughness);
create index idx_card_faces_loyalty      on card_faces (loyalty);
create index idx_card_faces_image_small  on card_faces (image_small);
create index idx_card_faces_image_normal on card_faces (image_normal);
create index idx_card_faces_image_large  on card_faces (image_large);
create index idx_card_faces_image_png    on card_faces (image_png);

create table legalities (
    id             bigint generated by default as identity primary key,
    oracle_card_id bigint      not null references card_oracles (id) on delete cascade,
    format         varchar(32) not null,
    status         varchar(32) not null,
    unique (oracle_card_id, format)
);
create index idx_legalities_oracle_card_id on legalities (oracle_card_id);
create index idx_legalities_format         on legalities (format);
create index idx_legalities_status         on legalities (status);
create index idx_legalities_format_status  on legalities (format, status);

create table rulings (
    id             bigint generated by default as identity primary key,
    oracle_card_id bigint not null references card_oracles (id) on delete cascade,
    source         varchar(32),
    published_at   date,
    comment        text   not null
);
create index idx_rulings_oracle_card_id on rulings (oracle_card_id);
create index idx_rulings_source         on rulings (source);
create index idx_rulings_published_at   on rulings (published_at);
create index idx_rulings_comment_trgm   on rulings using gin (comment gin_trgm_ops);

create table card_sync_runs (
    id              bigint generated by default as identity primary key,
    source          varchar(32) not null,
    bulk_type       varchar(64),
    status          varchar(32) not null,
    started_at      timestamptz not null default now(),
    finished_at     timestamptz,
    download_bytes  bigint,
    content_hash    varchar(128),
    total_processed integer     not null default 0,
    inserted_count  integer     not null default 0,
    updated_count   integer     not null default 0,
    error_count     integer     not null default 0,
    message         text
);
create index idx_card_sync_runs_source          on card_sync_runs (source);
create index idx_card_sync_runs_bulk_type       on card_sync_runs (bulk_type);
create index idx_card_sync_runs_status          on card_sync_runs (status);
create index idx_card_sync_runs_started_at      on card_sync_runs (started_at desc);
create index idx_card_sync_runs_finished_at     on card_sync_runs (finished_at);
create index idx_card_sync_runs_download_bytes  on card_sync_runs (download_bytes);
create index idx_card_sync_runs_content_hash    on card_sync_runs (content_hash);
create index idx_card_sync_runs_total_processed on card_sync_runs (total_processed);
create index idx_card_sync_runs_inserted_count  on card_sync_runs (inserted_count);
create index idx_card_sync_runs_updated_count   on card_sync_runs (updated_count);
create index idx_card_sync_runs_error_count     on card_sync_runs (error_count);
create index idx_card_sync_runs_message_trgm    on card_sync_runs using gin (message gin_trgm_ops);
