create table users (
    id             bigint generated by default as identity primary key,
    username       varchar(64)  not null unique,
    display_name   varchar(128) not null,
    email          varchar(255) not null unique,
    email_verified boolean      not null default false,
    password_hash  varchar(255),
    avatar_url     varchar(512),
    provider       varchar(32)  not null default 'LOCAL',
    provider_id    varchar(191),
    status         varchar(32)  not null default 'OFFLINE',
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now(),
    unique (provider, provider_id)
);
create index idx_users_username       on users (username);
create index idx_users_display_name   on users (display_name);
create index idx_users_email          on users (email);
create index idx_users_email_verified on users (email_verified);
create index idx_users_password_hash  on users (password_hash);
create index idx_users_avatar_url     on users (avatar_url);
create index idx_users_provider       on users (provider);
create index idx_users_provider_id    on users (provider_id);
create index idx_users_status         on users (status);
create index idx_users_created_at     on users (created_at);
create index idx_users_updated_at     on users (updated_at);

create table roles (
    id   bigint generated by default as identity primary key,
    name varchar(32) not null unique
);
create index idx_roles_name on roles (name);

create table user_roles (
    user_id bigint not null references users (id) on delete cascade,
    role_id bigint not null references roles (id) on delete cascade,
    primary key (user_id, role_id)
);
create index idx_user_roles_user_id on user_roles (user_id);
create index idx_user_roles_role_id on user_roles (role_id);

create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null references users (id) on delete cascade,
    token_hash varchar(128) not null unique,
    expires_at timestamptz  not null,
    revoked    boolean      not null default false,
    created_at timestamptz  not null default now(),
    user_agent varchar(255),
    ip         varchar(64)
);
create index idx_refresh_tokens_user_id    on refresh_tokens (user_id);
create index idx_refresh_tokens_token_hash on refresh_tokens (token_hash);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);
create index idx_refresh_tokens_revoked    on refresh_tokens (revoked);
create index idx_refresh_tokens_created_at on refresh_tokens (created_at);
create index idx_refresh_tokens_user_agent on refresh_tokens (user_agent);
create index idx_refresh_tokens_ip         on refresh_tokens (ip);

insert into roles (name) values ('USER'), ('MODERATOR'), ('ADMIN');
