create table formats (
    code                  varchar(32) primary key,
    name                  varchar(64)  not null,
    min_deck              integer,
    max_deck              integer,
    max_copies            integer      not null default 4,
    singleton             boolean      not null default false,
    uses_command_zone     boolean      not null default false,
    default_life          integer      not null default 20,
    enforce_color_identity boolean     not null default false,
    sideboard_max         integer      not null default 15,
    sort_order            integer      not null default 100
);
create index idx_formats_name       on formats (name);
create index idx_formats_min_deck   on formats (min_deck);
create index idx_formats_max_deck   on formats (max_deck);
create index idx_formats_max_copies on formats (max_copies);
create index idx_formats_singleton  on formats (singleton);
create index idx_formats_uses_cz    on formats (uses_command_zone);
create index idx_formats_life       on formats (default_life);
create index idx_formats_color_id   on formats (enforce_color_identity);
create index idx_formats_sb_max     on formats (sideboard_max);
create index idx_formats_sort_order on formats (sort_order);

insert into formats (code, name, min_deck, max_deck, max_copies, singleton, uses_command_zone, default_life, enforce_color_identity, sideboard_max, sort_order) values
    ('commander',   'Commander',   100, 100, 1, true,  true,  40, true,  0,  10),
    ('brawl',       'Brawl',       100, 100, 1, true,  true,  20, true,  0,  20),
    ('oathbreaker', 'Oathbreaker',  60,  60, 1, true,  true,  20, true,  0,  30),
    ('standard',    'Standard',     60, null, 4, false, false, 20, false, 15, 40),
    ('pioneer',     'Pioneer',      60, null, 4, false, false, 20, false, 15, 50),
    ('modern',      'Modern',       60, null, 4, false, false, 20, false, 15, 60),
    ('legacy',      'Legacy',       60, null, 4, false, false, 20, false, 15, 70),
    ('vintage',     'Vintage',      60, null, 4, false, false, 20, false, 15, 80),
    ('pauper',      'Pauper',       60, null, 4, false, false, 20, false, 15, 90),
    ('casual',      'Casual',        0, null, 99, false, false, 20, false, 30, 200);

create table deck_folders (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null references users (id) on delete cascade,
    parent_id  bigint       references deck_folders (id) on delete cascade,
    name       varchar(120) not null,
    position   integer      not null default 0,
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now()
);
create index idx_deck_folders_user_id    on deck_folders (user_id);
create index idx_deck_folders_parent_id  on deck_folders (parent_id);
create index idx_deck_folders_name       on deck_folders (name);
create index idx_deck_folders_position   on deck_folders (position);
create index idx_deck_folders_created_at on deck_folders (created_at);
create index idx_deck_folders_updated_at on deck_folders (updated_at);
create unique index uq_deck_folders_sibling_name
    on deck_folders (user_id, coalesce(parent_id, 0), lower(name));

create table decks (
    id             bigint generated by default as identity primary key,
    user_id        bigint       not null references users (id) on delete cascade,
    folder_id      bigint       references deck_folders (id) on delete set null,
    name           varchar(160) not null,
    format         varchar(32)  not null references formats (code),
    description    text,
    visibility     varchar(16)  not null default 'PRIVATE',
    color_identity varchar(16)  not null default '',
    favorite       boolean      not null default false,
    position       integer      not null default 0,
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now()
);
create index idx_decks_user_id        on decks (user_id);
create index idx_decks_folder_id      on decks (folder_id);
create index idx_decks_name           on decks (name);
create index idx_decks_format         on decks (format);
create index idx_decks_visibility     on decks (visibility);
create index idx_decks_color_identity on decks (color_identity);
create index idx_decks_favorite       on decks (favorite);
create index idx_decks_position       on decks (position);
create index idx_decks_created_at     on decks (created_at);
create index idx_decks_updated_at     on decks (updated_at);

create table deck_cards (
    id             bigint generated by default as identity primary key,
    deck_id        bigint      not null references decks (id) on delete cascade,
    oracle_card_id bigint      not null references card_oracles (id) on delete cascade,
    printing_id    bigint      references card_printings (id) on delete set null,
    quantity       integer     not null default 1 check (quantity > 0),
    section        varchar(16) not null default 'MAINBOARD',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    unique (deck_id, oracle_card_id, section)
);
create index idx_deck_cards_deck_id        on deck_cards (deck_id);
create index idx_deck_cards_oracle_card_id on deck_cards (oracle_card_id);
create index idx_deck_cards_printing_id    on deck_cards (printing_id);
create index idx_deck_cards_quantity       on deck_cards (quantity);
create index idx_deck_cards_section        on deck_cards (section);
create index idx_deck_cards_created_at     on deck_cards (created_at);
create index idx_deck_cards_updated_at     on deck_cards (updated_at);
