create table custom_arts (
    id              bigint generated by default as identity primary key,
    user_id         bigint       not null references users (id) on delete cascade,
    oracle_card_id  bigint       not null references card_oracles (id) on delete cascade,
    base_printing_id bigint      references card_printings (id) on delete set null,
    label           varchar(120) not null,
    display_name    varchar(160),
    overlay_text    text,
    image_url       varchar(512) not null,
    thumb_url       varchar(512),
    source_url      varchar(512),
    art_zoom        numeric      not null default 1,
    art_offset_x    numeric      not null default 0,
    art_offset_y    numeric      not null default 0,
    name_bar        boolean      not null default false,
    text_bar        boolean      not null default false,
    created_at      timestamptz  not null default now(),
    updated_at      timestamptz  not null default now()
);
create index idx_custom_arts_user_id          on custom_arts (user_id);
create index idx_custom_arts_oracle_card_id   on custom_arts (oracle_card_id);
create index idx_custom_arts_base_printing_id on custom_arts (base_printing_id);
create index idx_custom_arts_label            on custom_arts (label);
create index idx_custom_arts_display_name     on custom_arts (display_name);
create index idx_custom_arts_overlay_text     on custom_arts using gin (overlay_text gin_trgm_ops);
create index idx_custom_arts_image_url        on custom_arts (image_url);
create index idx_custom_arts_thumb_url        on custom_arts (thumb_url);
create index idx_custom_arts_source_url       on custom_arts (source_url);
create index idx_custom_arts_art_zoom         on custom_arts (art_zoom);
create index idx_custom_arts_art_offset_x     on custom_arts (art_offset_x);
create index idx_custom_arts_art_offset_y     on custom_arts (art_offset_y);
create index idx_custom_arts_name_bar         on custom_arts (name_bar);
create index idx_custom_arts_text_bar         on custom_arts (text_bar);
create index idx_custom_arts_created_at       on custom_arts (created_at);
create index idx_custom_arts_updated_at       on custom_arts (updated_at);

alter table deck_cards add column custom_art_id bigint references custom_arts (id) on delete set null;
create index idx_deck_cards_custom_art_id on deck_cards (custom_art_id);
