create table rooms (
    id               bigint generated by default as identity primary key,
    room_code        varchar(12)  not null unique,
    host_user_id     bigint       not null references users (id) on delete cascade,
    name             varchar(120) not null,
    format           varchar(32)  not null references formats (code),
    max_players      integer      not null default 4 check (max_players between 2 and 6),
    password_hash    varchar(100),
    visibility       varchar(16)  not null default 'PRIVATE',
    allow_spectators boolean      not null default true,
    status           varchar(16)  not null default 'OPEN',
    current_game_id  bigint,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now()
);
create index idx_rooms_room_code       on rooms (room_code);
create index idx_rooms_host_user_id    on rooms (host_user_id);
create index idx_rooms_name            on rooms using gin (name gin_trgm_ops);
create index idx_rooms_format          on rooms (format);
create index idx_rooms_max_players     on rooms (max_players);
create index idx_rooms_password_hash   on rooms (password_hash);
create index idx_rooms_visibility      on rooms (visibility);
create index idx_rooms_allow_spectators on rooms (allow_spectators);
create index idx_rooms_status          on rooms (status);
create index idx_rooms_current_game_id on rooms (current_game_id);
create index idx_rooms_created_at      on rooms (created_at);
create index idx_rooms_updated_at      on rooms (updated_at);

create table room_players (
    id         bigint generated by default as identity primary key,
    room_id    bigint      not null references rooms (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    role       varchar(16) not null default 'PLAYER',
    deck_id    bigint      references decks (id) on delete set null,
    seat       integer,
    status     varchar(16) not null default 'JOINED',
    joined_at  timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (room_id, user_id)
);
create index idx_room_players_room_id    on room_players (room_id);
create index idx_room_players_user_id    on room_players (user_id);
create index idx_room_players_role       on room_players (role);
create index idx_room_players_deck_id    on room_players (deck_id);
create index idx_room_players_seat       on room_players (seat);
create index idx_room_players_status     on room_players (status);
create index idx_room_players_joined_at  on room_players (joined_at);
create index idx_room_players_updated_at on room_players (updated_at);

create table games (
    id            bigint generated by default as identity primary key,
    room_id       bigint      not null references rooms (id) on delete cascade,
    format        varchar(32) not null references formats (code),
    status        varchar(16) not null default 'ACTIVE',
    turn_number   integer     not null default 1,
    active_seat   integer     not null default 0,
    phase         varchar(16) not null default 'UNTAP',
    last_sequence bigint      not null default 0,
    created_by    bigint      not null references users (id) on delete cascade,
    created_at    timestamptz not null default now(),
    started_at    timestamptz,
    finished_at   timestamptz,
    updated_at    timestamptz not null default now()
);
create index idx_games_room_id       on games (room_id);
create index idx_games_format        on games (format);
create index idx_games_status        on games (status);
create index idx_games_turn_number   on games (turn_number);
create index idx_games_active_seat   on games (active_seat);
create index idx_games_phase         on games (phase);
create index idx_games_last_sequence on games (last_sequence);
create index idx_games_created_by    on games (created_by);
create index idx_games_created_at    on games (created_at);
create index idx_games_started_at    on games (started_at);
create index idx_games_finished_at   on games (finished_at);
create index idx_games_updated_at    on games (updated_at);

alter table rooms add constraint fk_rooms_current_game
    foreign key (current_game_id) references games (id) on delete set null;

create table game_players (
    id               bigint generated by default as identity primary key,
    game_id          bigint      not null references games (id) on delete cascade,
    user_id          bigint      not null references users (id) on delete cascade,
    seat             integer     not null,
    deck_id          bigint      references decks (id) on delete set null,
    life_total       integer     not null default 20,
    commander_damage jsonb       not null default '{}'::jsonb,
    counters         jsonb       not null default '{}'::jsonb,
    status           varchar(16) not null default 'PLAYING',
    connected        boolean     not null default true,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    unique (game_id, user_id),
    unique (game_id, seat)
);
create index idx_game_players_game_id          on game_players (game_id);
create index idx_game_players_user_id          on game_players (user_id);
create index idx_game_players_seat             on game_players (seat);
create index idx_game_players_deck_id          on game_players (deck_id);
create index idx_game_players_life_total       on game_players (life_total);
create index idx_game_players_commander_damage on game_players using gin (commander_damage);
create index idx_game_players_counters         on game_players using gin (counters);
create index idx_game_players_status           on game_players (status);
create index idx_game_players_connected        on game_players (connected);
create index idx_game_players_created_at       on game_players (created_at);
create index idx_game_players_updated_at       on game_players (updated_at);

create table game_cards (
    id                 bigint generated by default as identity primary key,
    game_id            bigint      not null references games (id) on delete cascade,
    owner_user_id      bigint      not null references users (id) on delete cascade,
    controller_user_id bigint      not null references users (id) on delete cascade,
    oracle_card_id     bigint      not null references card_oracles (id) on delete cascade,
    printing_id        bigint      references card_printings (id) on delete set null,
    custom_art_id      bigint      references custom_arts (id) on delete set null,
    zone               varchar(16) not null,
    position           integer     not null default 0,
    x                  numeric,
    y                  numeric,
    tapped             boolean     not null default false,
    face_down          boolean     not null default false,
    rotation           integer     not null default 0,
    counters           jsonb       not null default '{}'::jsonb,
    revealed_to        jsonb       not null default '[]'::jsonb,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);
create index idx_game_cards_game_id            on game_cards (game_id);
create index idx_game_cards_owner_user_id      on game_cards (owner_user_id);
create index idx_game_cards_controller_user_id on game_cards (controller_user_id);
create index idx_game_cards_oracle_card_id     on game_cards (oracle_card_id);
create index idx_game_cards_printing_id        on game_cards (printing_id);
create index idx_game_cards_custom_art_id      on game_cards (custom_art_id);
create index idx_game_cards_zone               on game_cards (zone);
create index idx_game_cards_position           on game_cards (position);
create index idx_game_cards_x                  on game_cards (x);
create index idx_game_cards_y                  on game_cards (y);
create index idx_game_cards_tapped             on game_cards (tapped);
create index idx_game_cards_face_down          on game_cards (face_down);
create index idx_game_cards_rotation           on game_cards (rotation);
create index idx_game_cards_counters           on game_cards using gin (counters);
create index idx_game_cards_revealed_to        on game_cards using gin (revealed_to);
create index idx_game_cards_created_at         on game_cards (created_at);
create index idx_game_cards_updated_at         on game_cards (updated_at);
create index idx_game_cards_game_zone_owner    on game_cards (game_id, zone, owner_user_id);

create table game_events (
    id              bigint generated by default as identity primary key,
    game_id         bigint      not null references games (id) on delete cascade,
    sequence_number bigint      not null,
    actor_user_id   bigint      references users (id) on delete set null,
    event_type      varchar(32) not null,
    payload         jsonb       not null default '{}'::jsonb,
    log_line        text,
    created_at      timestamptz not null default now(),
    unique (game_id, sequence_number)
);
create index idx_game_events_game_id         on game_events (game_id);
create index idx_game_events_sequence_number on game_events (sequence_number);
create index idx_game_events_actor_user_id   on game_events (actor_user_id);
create index idx_game_events_event_type      on game_events (event_type);
create index idx_game_events_payload         on game_events using gin (payload);
create index idx_game_events_log_line        on game_events using gin (log_line gin_trgm_ops);
create index idx_game_events_created_at      on game_events (created_at);
create index idx_game_events_game_seq        on game_events (game_id, sequence_number);

create table chat_messages (
    id         bigint generated by default as identity primary key,
    room_id    bigint      not null references rooms (id) on delete cascade,
    game_id    bigint      references games (id) on delete cascade,
    user_id    bigint      references users (id) on delete set null,
    body       text        not null,
    kind       varchar(16) not null default 'USER',
    created_at timestamptz not null default now()
);
create index idx_chat_messages_room_id    on chat_messages (room_id);
create index idx_chat_messages_game_id    on chat_messages (game_id);
create index idx_chat_messages_user_id    on chat_messages (user_id);
create index idx_chat_messages_body       on chat_messages using gin (body gin_trgm_ops);
create index idx_chat_messages_kind       on chat_messages (kind);
create index idx_chat_messages_created_at on chat_messages (created_at);
