create table card_translations (
    id             bigint       generated by default as identity primary key,
    oracle_card_id bigint       not null references card_oracles (id) on delete cascade,
    lang           varchar(8)   not null default 'pt',
    name           varchar(512),
    type_line      varchar(512),
    oracle_text    text,
    source         varchar(16)  not null,
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now(),
    constraint uq_card_translations_oracle_lang unique (oracle_card_id, lang)
);

create index idx_card_translations_oracle_card_id on card_translations (oracle_card_id);
create index idx_card_translations_lang           on card_translations (lang);
create index idx_card_translations_name           on card_translations using gin (name gin_trgm_ops);
create index idx_card_translations_type_line      on card_translations using gin (type_line gin_trgm_ops);
create index idx_card_translations_oracle_text    on card_translations using gin (oracle_text gin_trgm_ops);
create index idx_card_translations_source         on card_translations (source);
create index idx_card_translations_created_at     on card_translations (created_at);
create index idx_card_translations_updated_at     on card_translations (updated_at);
