drop index if exists idx_sets_name;
drop index if exists idx_sets_set_type;
drop index if exists idx_sets_card_count;
drop index if exists idx_sets_scryfall_id;
drop index if exists idx_sets_icon_svg_uri;
drop index if exists idx_sets_created_at;
drop index if exists idx_sets_updated_at;

drop index if exists idx_card_oracles_name;
drop index if exists idx_card_oracles_mana_cost;
drop index if exists idx_card_oracles_mana_value;
drop index if exists idx_card_oracles_type_line;
drop index if exists idx_card_oracles_type_line_trgm;
drop index if exists idx_card_oracles_oracle_text;
drop index if exists idx_card_oracles_colors;
drop index if exists idx_card_oracles_color_identity;
drop index if exists idx_card_oracles_power;
drop index if exists idx_card_oracles_toughness;
drop index if exists idx_card_oracles_loyalty;
drop index if exists idx_card_oracles_keywords;
drop index if exists idx_card_oracles_layout;
drop index if exists idx_card_oracles_reserved;
drop index if exists idx_card_oracles_edhrec_rank;
drop index if exists idx_card_oracles_created_at;
drop index if exists idx_card_oracles_updated_at;

drop index if exists idx_card_printings_set_id;
drop index if exists idx_card_printings_set_code;
drop index if exists idx_card_printings_collector_number;
drop index if exists idx_card_printings_set_code_number;
drop index if exists idx_card_printings_rarity;
drop index if exists idx_card_printings_artist;
drop index if exists idx_card_printings_flavor_text;
drop index if exists idx_card_printings_lang;
drop index if exists idx_card_printings_layout;
drop index if exists idx_card_printings_border_color;
drop index if exists idx_card_printings_frame;
drop index if exists idx_card_printings_promo;
drop index if exists idx_card_printings_variation;
drop index if exists idx_card_printings_full_art;
drop index if exists idx_card_printings_image_small;
drop index if exists idx_card_printings_image_normal;
drop index if exists idx_card_printings_image_large;
drop index if exists idx_card_printings_image_png;
drop index if exists idx_card_printings_image_art_crop;
drop index if exists idx_card_printings_image_border_crop;
drop index if exists idx_card_printings_released_at;
drop index if exists idx_card_printings_scryfall_uri;
drop index if exists idx_card_printings_created_at;
drop index if exists idx_card_printings_updated_at;

drop index if exists idx_card_faces_face_index;
drop index if exists idx_card_faces_name;
drop index if exists idx_card_faces_name_trgm;
drop index if exists idx_card_faces_mana_cost;
drop index if exists idx_card_faces_type_line;
drop index if exists idx_card_faces_oracle_text;
drop index if exists idx_card_faces_colors;
drop index if exists idx_card_faces_power;
drop index if exists idx_card_faces_toughness;
drop index if exists idx_card_faces_loyalty;
drop index if exists idx_card_faces_image_small;
drop index if exists idx_card_faces_image_normal;
drop index if exists idx_card_faces_image_large;
drop index if exists idx_card_faces_image_png;

drop index if exists idx_legalities_oracle_card_id;
drop index if exists idx_legalities_format;
drop index if exists idx_legalities_status;
drop index if exists idx_legalities_format_status;

drop index if exists idx_rulings_source;
drop index if exists idx_rulings_published_at;
drop index if exists idx_rulings_comment_trgm;

drop index if exists idx_card_sync_runs_source;
drop index if exists idx_card_sync_runs_bulk_type;
drop index if exists idx_card_sync_runs_started_at;
drop index if exists idx_card_sync_runs_finished_at;
drop index if exists idx_card_sync_runs_download_bytes;
drop index if exists idx_card_sync_runs_content_hash;
drop index if exists idx_card_sync_runs_total_processed;
drop index if exists idx_card_sync_runs_inserted_count;
drop index if exists idx_card_sync_runs_updated_count;
drop index if exists idx_card_sync_runs_error_count;
drop index if exists idx_card_sync_runs_message_trgm;

drop index if exists idx_users_email;
drop index if exists idx_users_username;
drop index if exists idx_users_display_name;
drop index if exists idx_users_email_verified;
drop index if exists idx_users_password_hash;
drop index if exists idx_users_avatar_url;
drop index if exists idx_users_provider;
drop index if exists idx_users_provider_id;
drop index if exists idx_users_status;
drop index if exists idx_users_created_at;
drop index if exists idx_users_updated_at;
create index if not exists idx_users_email_lower    on users (lower(email));
create index if not exists idx_users_username_lower on users (lower(username));

drop index if exists idx_roles_name;
drop index if exists idx_user_roles_user_id;
drop index if exists idx_user_roles_role_id;

drop index if exists idx_refresh_tokens_token_hash;
drop index if exists idx_refresh_tokens_expires_at;
drop index if exists idx_refresh_tokens_revoked;
drop index if exists idx_refresh_tokens_created_at;
drop index if exists idx_refresh_tokens_user_agent;
drop index if exists idx_refresh_tokens_ip;

drop index if exists idx_formats_name;
drop index if exists idx_formats_min_deck;
drop index if exists idx_formats_max_deck;
drop index if exists idx_formats_max_copies;
drop index if exists idx_formats_singleton;
drop index if exists idx_formats_uses_cz;
drop index if exists idx_formats_life;
drop index if exists idx_formats_color_id;
drop index if exists idx_formats_sb_max;
drop index if exists idx_formats_sort_order;

drop index if exists idx_deck_folders_parent_id;
drop index if exists idx_deck_folders_name;
drop index if exists idx_deck_folders_position;
drop index if exists idx_deck_folders_created_at;
drop index if exists idx_deck_folders_updated_at;

drop index if exists idx_decks_name;
drop index if exists idx_decks_format;
drop index if exists idx_decks_visibility;
drop index if exists idx_decks_color_identity;
drop index if exists idx_decks_favorite;
drop index if exists idx_decks_position;
drop index if exists idx_decks_created_at;
drop index if exists idx_decks_updated_at;

drop index if exists idx_deck_cards_deck_id;
drop index if exists idx_deck_cards_oracle_card_id;
drop index if exists idx_deck_cards_printing_id;
drop index if exists idx_deck_cards_quantity;
drop index if exists idx_deck_cards_section;
drop index if exists idx_deck_cards_created_at;
drop index if exists idx_deck_cards_updated_at;

drop index if exists idx_custom_arts_oracle_card_id;
drop index if exists idx_custom_arts_base_printing_id;
drop index if exists idx_custom_arts_label;
drop index if exists idx_custom_arts_display_name;
drop index if exists idx_custom_arts_overlay_text;
drop index if exists idx_custom_arts_image_url;
drop index if exists idx_custom_arts_thumb_url;
drop index if exists idx_custom_arts_source_url;
drop index if exists idx_custom_arts_art_zoom;
drop index if exists idx_custom_arts_art_offset_x;
drop index if exists idx_custom_arts_art_offset_y;
drop index if exists idx_custom_arts_name_bar;
drop index if exists idx_custom_arts_text_bar;
drop index if exists idx_custom_arts_created_at;
drop index if exists idx_custom_arts_updated_at;

drop index if exists idx_rooms_room_code;
drop index if exists idx_rooms_name;
drop index if exists idx_rooms_format;
drop index if exists idx_rooms_max_players;
drop index if exists idx_rooms_password_hash;
drop index if exists idx_rooms_allow_spectators;
drop index if exists idx_rooms_visibility;
drop index if exists idx_rooms_status;
drop index if exists idx_rooms_current_game_id;
drop index if exists idx_rooms_created_at;
drop index if exists idx_rooms_updated_at;
create index if not exists idx_rooms_visibility_status on rooms (visibility, status);

drop index if exists idx_room_players_room_id;
drop index if exists idx_room_players_role;
drop index if exists idx_room_players_deck_id;
drop index if exists idx_room_players_seat;
drop index if exists idx_room_players_status;
drop index if exists idx_room_players_joined_at;
drop index if exists idx_room_players_updated_at;

drop index if exists idx_games_format;
drop index if exists idx_games_status;
drop index if exists idx_games_turn_number;
drop index if exists idx_games_active_seat;
drop index if exists idx_games_phase;
drop index if exists idx_games_last_sequence;
drop index if exists idx_games_created_by;
drop index if exists idx_games_created_at;
drop index if exists idx_games_started_at;
drop index if exists idx_games_finished_at;
drop index if exists idx_games_updated_at;

drop index if exists idx_game_players_game_id;
drop index if exists idx_game_players_user_id;
drop index if exists idx_game_players_seat;
drop index if exists idx_game_players_deck_id;
drop index if exists idx_game_players_life_total;
drop index if exists idx_game_players_commander_damage;
drop index if exists idx_game_players_counters;
drop index if exists idx_game_players_status;
drop index if exists idx_game_players_connected;
drop index if exists idx_game_players_created_at;
drop index if exists idx_game_players_updated_at;

drop index if exists idx_game_cards_game_id;
drop index if exists idx_game_cards_owner_user_id;
drop index if exists idx_game_cards_controller_user_id;
drop index if exists idx_game_cards_oracle_card_id;
drop index if exists idx_game_cards_printing_id;
drop index if exists idx_game_cards_custom_art_id;
drop index if exists idx_game_cards_zone;
drop index if exists idx_game_cards_position;
drop index if exists idx_game_cards_x;
drop index if exists idx_game_cards_y;
drop index if exists idx_game_cards_tapped;
drop index if exists idx_game_cards_face_down;
drop index if exists idx_game_cards_rotation;
drop index if exists idx_game_cards_counters;
drop index if exists idx_game_cards_revealed_to;
drop index if exists idx_game_cards_created_at;
drop index if exists idx_game_cards_updated_at;
drop index if exists idx_game_cards_is_token;
drop index if exists idx_game_cards_token_name;
drop index if exists idx_game_cards_token_pt;
drop index if exists idx_game_cards_token_colors;
drop index if exists idx_game_cards_token_text;

drop index if exists idx_game_events_game_id;
drop index if exists idx_game_events_sequence_number;
drop index if exists idx_game_events_actor_user_id;
drop index if exists idx_game_events_event_type;
drop index if exists idx_game_events_payload;
drop index if exists idx_game_events_log_line;
drop index if exists idx_game_events_created_at;
drop index if exists idx_game_events_game_seq;

drop index if exists idx_chat_messages_room_id;
drop index if exists idx_chat_messages_game_id;
drop index if exists idx_chat_messages_user_id;
drop index if exists idx_chat_messages_body;
drop index if exists idx_chat_messages_kind;
drop index if exists idx_chat_messages_created_at;
create index if not exists idx_chat_messages_room_created on chat_messages (room_id, created_at desc);

drop index if exists idx_card_translations_oracle_card_id;
drop index if exists idx_card_translations_lang;
drop index if exists idx_card_translations_name;
drop index if exists idx_card_translations_type_line;
drop index if exists idx_card_translations_oracle_text;
drop index if exists idx_card_translations_source;
drop index if exists idx_card_translations_created_at;
drop index if exists idx_card_translations_updated_at;
