create table user_permissions (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    permission varchar(64) not null,
    granted_by bigint      references users (id) on delete set null,
    granted_at timestamptz not null default now(),
    constraint uq_user_permissions unique (user_id, permission)
);

create index idx_user_permissions_user_id on user_permissions (user_id);
